package NewStudentData;


/**
* NewStudentData/StudentData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NewStudentData.idl
* Friday, March 25, 2016 5:37:20 PM PDT
*/

public interface StudentData extends StudentDataOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StudentData
