package NewStudentData;


/**
* NewStudentData/StudentDataOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NewStudentData.idl
* Friday, March 25, 2016 5:37:20 PM PDT
*/

public interface StudentDataOperations 
{
  int StudID ();
  void StudID (int newStudID);
  String Name ();
  void Name (String newName);
  String SSN ();
  void SSN (String newSSN);
  String EmailAddress ();
  void EmailAddress (String newEmailAddress);
  String HomePhone ();
  void HomePhone (String newHomePhone);
} // interface StudentDataOperations
