package NewStudentData;

/**
* NewStudentData/StudentDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NewStudentData.idl
* Friday, March 25, 2016 5:37:20 PM PDT
*/

public final class StudentDataHolder implements org.omg.CORBA.portable.Streamable
{
  public NewStudentData.StudentData value = null;

  public StudentDataHolder ()
  {
  }

  public StudentDataHolder (NewStudentData.StudentData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NewStudentData.StudentDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NewStudentData.StudentDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NewStudentData.StudentDataHelper.type ();
  }

}
